.TH "/home/allandemiranda/Documentos/Hash-Leva-Jeito/include Directory Reference" 3 "Fri Sep 27 2019" "Operação “Leva Jeito”" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/allandemiranda/Documentos/Hash-Leva-Jeito/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCheckHashTable\&.hpp\fP"
.br
.RI "Classe para comparar os arquivos com o da tabela de configuraçao\&. "
.ti -1c
.RI "file \fBCreateHashTable\&.hpp\fP"
.br
.RI "Classe para a criação do arquivo de configuração\&. "
.ti -1c
.RI "file \fBGuarda\&.hpp\fP"
.br
.RI "Classe de controle\&. "
.ti -1c
.RI "file \fBHashFile\&.hpp\fP"
.br
.RI "Classe que cria a hash para o arquivo solicitado\&. "
.ti -1c
.RI "file \fBLog\&.hpp\fP"
.br
.RI "Classe para gerenciar o modelo de logs\&. "
.ti -1c
.RI "file \fBOpenLogFile\&.hpp\fP"
.br
.RI "Classe para abrir arquivos de log de acordo com o padrão solicitado\&. "
.ti -1c
.RI "file \fBReadingFolderFiles\&.hpp\fP"
.br
.RI "Classe para gerenciar a leitura de todos os arquivos de todas as pastas\&. "
.ti -1c
.RI "file \fBReportOutput\&.hpp\fP"
.br
.RI "Classe para gerenciar saída de arquivo de log\&. "
.in -1c
