.TH "/home/allandemiranda/Documentos/Hash-Leva-Jeito/src/Guarda.cpp" 3 "Fri Sep 27 2019" "Operação “Leva Jeito”" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/allandemiranda/Documentos/Hash-Leva-Jeito/src/Guarda.cpp \- Métodos para classe \fBGuarda\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Guarda\&.hpp'\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'CheckHashTable\&.hpp'\fP
.br
\fC#include 'CreateHashTable\&.hpp'\fP
.br
\fC#include 'OpenLogFile\&.hpp'\fP
.br
\fC#include 'ReadingFolderFiles\&.hpp'\fP
.br
\fC#include 'ReportOutput\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Métodos para classe \fBGuarda\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
Allan de Miranda Silva (allandemiranda@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.2 
.RE
.PP
\fBDate:\fP
.RS 4
25-09-2019
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2019 
.RE
.PP

.PP
Definition in file \fBGuarda\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Operação “Leva Jeito” from the source code\&.
