.TH "/home/allandemiranda/Documentos/Hash-Leva-Jeito/include/HashFile.hpp" 3 "Fri Sep 27 2019" "Operação “Leva Jeito”" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/allandemiranda/Documentos/Hash-Leva-Jeito/include/HashFile.hpp \- Classe que cria a hash para o arquivo solicitado\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHashFile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classe que cria a hash para o arquivo solicitado\&. 


.PP
\fBAuthor:\fP
.RS 4
Allan de Miranda Silva (allandemiranda@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
25-09-2019
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2019 
.RE
.PP

.PP
Definition in file \fBHashFile\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Operação “Leva Jeito” from the source code\&.
