.TH "/home/allandemiranda/Documentos/Hash-Leva-Jeito/src/HashFile.cpp" 3 "Fri Sep 27 2019" "Operação “Leva Jeito”" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/allandemiranda/Documentos/Hash-Leva-Jeito/src/HashFile.cpp \- Métodos para classe \fBHashFile\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'HashFile\&.hpp'\fP
.br
\fC#include <openssl/hmac\&.h>\fP
.br
\fC#include <openssl/md5\&.h>\fP
.br
\fC#include <boost/iostreams/device/mapped_file\&.hpp>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <sstream>\fP
.br

.SH "Detailed Description"
.PP 
Métodos para classe \fBHashFile\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
Allan de Miranda Silva (allandemiranda@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
25-09-2019
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2019 
.RE
.PP

.PP
Definition in file \fBHashFile\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Operação “Leva Jeito” from the source code\&.
