.TH "/home/allandemiranda/Documentos/Hash-Leva-Jeito/src/main.cpp" 3 "Fri Sep 27 2019" "Operação “Leva Jeito”" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/allandemiranda/Documentos/Hash-Leva-Jeito/src/main.cpp \- Main\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <getopt\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Guarda\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.RI "Função main\&. "
.in -1c
.SH "Detailed Description"
.PP 
Main\&. 


.PP
\fBAuthor:\fP
.RS 4
Allan de Miranda Silva (allandemiranda@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.2 
.RE
.PP
\fBDate:\fP
.RS 4
25-09-2019
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2019 
.RE
.PP

.PP
Definition in file \fBmain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Função main\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargc\fP Quantidade de argumentos 
.br
\fIargv\fP Argumentos de entrada 
.RE
.PP
\fBReturns:\fP
.RS 4
int return 
.RE
.PP

.PP
Definition at line 24 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Operação “Leva Jeito” from the source code\&.
