.TH "/home/allandemiranda/Documentos/Hash-Leva-Jeito/README.md" 3 "Fri Sep 27 2019" "Operação “Leva Jeito”" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/allandemiranda/Documentos/Hash-Leva-Jeito/README.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Operação “Leva Jeito” from the source code\&.
