.TH "/home/allandemiranda/Documentos/Hash-Leva-Jeito/src/ReadingFolderFiles.cpp" 3 "Fri Sep 27 2019" "Operação “Leva Jeito”" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/allandemiranda/Documentos/Hash-Leva-Jeito/src/ReadingFolderFiles.cpp \- Métodos da classe \fBReadingFolderFiles\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ReadingFolderFiles\&.hpp'\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SH "Detailed Description"
.PP 
Métodos da classe \fBReadingFolderFiles\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
Allan de Miranda Silva (allandemiranda@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
25-09-2019
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2019 
.RE
.PP

.PP
Definition in file \fBReadingFolderFiles\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Operação “Leva Jeito” from the source code\&.
