.TH "ReadingFolderFiles" 3 "Fri Sep 27 2019" "Operação “Leva Jeito”" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReadingFolderFiles
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ReadingFolderFiles\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::vector< std::string > \fBgetListPath\fP (void)"
.br
.RI "Get the List Path object\&. "
.ti -1c
.RI "\fBReadingFolderFiles\fP (std::string)"
.br
.RI "Construct a new Reading Folder Files:: Reading Folder Files object\&. "
.ti -1c
.RI "\fB~ReadingFolderFiles\fP (void)"
.br
.RI "Destroy the Reading Folder Files:: Reading Folder Files object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file ReadingFolderFiles\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ReadingFolderFiles::ReadingFolderFiles (std::string loop_path)"

.PP
Construct a new Reading Folder Files:: Reading Folder Files object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIloop_path\fP Caminho para analisar 
.RE
.PP

.PP
Definition at line 23 of file ReadingFolderFiles\&.cpp\&.
.SS "ReadingFolderFiles::~ReadingFolderFiles (void)"

.PP
Destroy the Reading Folder Files:: Reading Folder Files object\&. 
.PP
Definition at line 31 of file ReadingFolderFiles\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::vector< std::string > ReadingFolderFiles::getListPath (void)"

.PP
Get the List Path object\&. 
.PP
\fBReturns:\fP
.RS 4
std::vector<std::string> Lista de caminhos de arquivos encontrados 
.RE
.PP

.PP
Definition at line 38 of file ReadingFolderFiles\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Operação “Leva Jeito” from the source code\&.
