.TH "ReportOutput" 3 "Fri Sep 27 2019" "Operação “Leva Jeito”" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReportOutput
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ReportOutput\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReportOutput\fP (std::vector< \fBLog\fP >, std::string)"
.br
.RI "Construct a new Report Output:: Report Output object\&. "
.ti -1c
.RI "\fB~ReportOutput\fP (void)"
.br
.RI "Destroy the Report Output:: Report Output object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file ReportOutput\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ReportOutput::ReportOutput (std::vector< \fBLog\fP > logs, std::string path)"

.PP
Construct a new Report Output:: Report Output object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlogs\fP Vetor com os logs a ser salvo em um arquivo de texto 
.br
\fIpath\fP Caminho do arquivo para salvar 
.RE
.PP

.PP
Definition at line 27 of file ReportOutput\&.cpp\&.
.SS "ReportOutput::~ReportOutput (void)"

.PP
Destroy the Report Output:: Report Output object\&. 
.PP
Definition at line 35 of file ReportOutput\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Operação “Leva Jeito” from the source code\&.
